apiVersion: apps.emqx.io/v2beta1
kind: Rebalance
metadata:
  namespace: emqx
  name: rebalance
spec:
  instanceName: emqx
  rebalanceStrategy:
    connEvictRate: 10
    sessEvictRate: 10
    waitTakeover: 10
    waitHealthCheck: 10
    absConnThreshold: 100
    absSessThreshold: 100
    relConnThreshold: "1.1"
    relSessThreshold: "1.1"
